### ISSUE TITLE
wd-slider 这个组件有问题，我把例子放到代码中，没有改动，就直接粘贴上去，就出错误了，

### ISSUE THREAD

**Issue by 5565007** [Moonofweisheng/wot-design-uni#226]
### Wot Design Uni 版本号

0.1.1

### 平台

h5

### 重现链接

无

### 重现步骤

直接提示下面的错误

main.ts:1 ReferenceError: Cannot access 'emit' before initialization
    at leftBarSlider (wd-slider.vue:293:5)
    at watch.deep (wd-slider.vue:166:7)
    at callWithErrorHandling (vue.runtime.esm.js:1376:1)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1385:1)
    at job (vue.runtime.esm.js:3073:1)
    at doWatch (vue.runtime.esm.js:3116:1)
    at watch (vue.runtime.esm.js:2949:1)
    at setup (wd-slider.vue:139:1)
    at callWithErrorHandling (vue.runtime.esm.js:1376:1)
    at setupStatefulComponent (vue.runtime.esm.js:8654:1)

### 期望的结果是什么？

期望修复一下

### 实际的结果是什么？

期望修复一下

**Comment by Moonofweisheng** [comment]
uniapp和vue版本提供一下吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月8日(周一) 下午3:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] wd-slider 这个组件有问题，我把例子放到代码中，没有改动，就直接粘贴上去，就出错误了， (Issue #226)




 
Wot Design Uni 版本号
 
0.1.1
 
平台
 
h5
 
重现链接
 
无
 
重现步骤
 
直接提示下面的错误
 
main.ts:1 ReferenceError: Cannot access 'emit' before initialization
 at leftBarSlider (wd-slider.vue:293:5)
 at watch.deep (wd-slider.vue:166:7)
 at callWithErrorHandling (vue.runtime.esm.js:1376:1)
 at callWithAsyncErrorHandling (vue.runtime.esm.js:1385:1)
 at job (vue.runtime.esm.js:3073:1)
 at doWatch (vue.runtime.esm.js:3116:1)
 at watch (vue.runtime.esm.js:2949:1)
 at setup (wd-slider.vue:139:1)
 at callWithErrorHandling (vue.runtime.esm.js:1376:1)
 at setupStatefulComponent (vue.runtime.esm.js:8654:1)
 
期望的结果是什么？
 
期望修复一下
 
实际的结果是什么？
 
期望修复一下
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by Moonofweisheng** [comment]
uni-app 版本先退到3.99吧，这个问题下个版本修复
